---
useGithubReleasesForUpdateReminder: false
showSeakbarOnUpdate: true
showNotificationOnUpdate: true
enabled: true
versionCode: 34
versionUrl: "https://abertschi.github.io/ad-free/landing/"
versionNotify: false
...
