---
useGithubReleasesForUpdateReminder: false
showSeakbarOnUpdate: true
showNotificationOnUpdate: true
showMessageOnStart: false
messageOnStartTitle: ""
messageOnStartContent: ""
showMessageOnUse: false
messageOnUseTitle: ""
messageOnUseContent: ""
enabled: true
...
