---
useGithubReleasesForUpdateReminder: true
showSeakbarOnUpdate: false
showNotificationOnUpdate: true
showMessageOnStart: true
messageOnStartTitle: "4"
messageOnStartContent: "3"
showMessageOnUse: true
messageOnUseTitle: "2"
messageOnUseContent: "1"
enabled: false
...
