---
useGithubReleasesForUpdateReminder: false
showSeakbarOnUpdate: true
showNotificationOnUpdate: true
enabled: true
versionCode: 35
versionUrl: "https://abertschi.github.io/ad-free/landing/"
versionNotify: true
...
